# Site settings
title: "Jack Serrino's Home"
email: "jserrino@mit.edu"
description: "The home and blog of Jack Serrino"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
