# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jack Serrino

description: Because everyone needs a web presence.
author:
  name: Jack Serrino
  email: jserrino@mit.edu
  github: Detry322
  twitter: Detry322
  linkedin: JackSerrino
  bio: "Hi! I'm Jack Serrino, a member of MIT's class of 2018. I love Math, Computer Science, Physics, and Volleyball.<br /><br />Below you will find links to various social media profiles."
  email_md5: 6a1748b5769f762bbd743dcdcb134b45

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
