# Site settings
title: "Jack Serrino"
email: "jserrino@mit.edu"
description: "Because in this day and age, everyone needs a website"
baseurl: ""
url: "http://jackserrino.com"
twitter_username: Detry322
github_username:  Detry322

# Build settings
markdown: kramdown
permalink: pretty
